# Read in Refugee Data
---
Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Extracted:,"United Nations High Commissioner for Refugees"
"Date extracted:","08/03/2022 13:39 UTC"
"Last updated:","10 November 2021"
"Some data presented may differ from statistics published previously due to retroactive changes or the inclusion of previously unavailable data."

"Data table contains the following:","Population figures"
"Content type","End year stock population totals"
"Data quick link",https://www.unhcr.org/refugee-statistics/download/?url=VHI7gj
"Data definitions",https://www.unhcr.org/refugee-statistics/methodology/
"Usage licence",https://creativecommons.org/licenses/by/4.0/
"Population types included","REF,ROC,ASY,IDP,IOC,VDA,OOC,STA"
Years:
Origin:,all
"Country of asylum:",all

In [9]:
df = pd.read_csv('../../data/Refugee data query_data (1)/population.csv')

In [10]:
df

,Year,Country of origin,Country of origin (ISO),Country of asylum,Country of asylum (ISO),Refugees under UNHCR's mandate,Asylum-seekers,IDPs of concern to UNHCR,Venezuelans displaced abroad,Stateless persons,Others of concern
0,2016,Afghanistan,AFG,Afghanistan,AFG,0,0,1797551,NaN,0,114221
1,2016,Afghanistan,AFG,Egypt,EGY,14,21,0,NaN,0,0
2,2016,Afghanistan,AFG,Argentina,ARG,5,0,0,NaN,0,0
3,2016,Afghanistan,AFG,Australia,AUS,9217,2077,0,NaN,0,0
4,2016,Afghanistan,AFG,Austria,AUT,20220,29783,0,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...
31741,2021,Zimbabwe,ZWE,Sweden,SWE,17,13,0,NaN,0,0
31742,2021,Zimbabwe,ZWE,Switzerland,CHE,9,5,0,NaN,0,0
31743,2021,Zimbabwe,ZWE,Thailand,THA,9,0,0,NaN,0,0
31744,2021,Zimbabwe,ZWE,United States of America,USA,729,1238,0,NaN,0,0
31745,2021,Zimbabwe,ZWE,Zimbabwe,ZWE,0,0,0,NaN,0,141

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31746 entries, 0 to 31745
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            31746 non-null  int64
 1   Country of origin               31746 non-null  object
 2   Country of origin (ISO)         31447 non-null  object
 3   Country of asylum               31746 non-null  object
 4   Country of asylum (ISO)         31746 non-null  object
 5   Refugees under UNHCR's mandate  31746 non-null  int64
 6   Asylum-seekers                  31746 non-null  int64
 7   IDPs of concern to UNHCR        31746 non-null  int64
 8   Venezuelans displaced abroad    83 non-null     float64
 9   Stateless persons               31746 non-null  int64
 10  Others of concern               31746 non-null  int64
dtypes: float64(1), int64(6), object(4)
memory usage: 2.7+ MB

In [12]:
df.isnull().sum()

Year                                  0
Country of origin                     0
Country of origin (ISO)             299
Country of asylum                     0
Country of asylum (ISO)               0
Refugees under UNHCR's mandate        0
Asylum-seekers                        0
IDPs of concern to UNHCR              0
Venezuelans displaced abroad      31663
Stateless persons                     0
Others of concern                     0
dtype: int64

In [13]:
df.drop(columns ='Venezuelans displaced abroad', inplace = True)

In [14]:
df.isnull().sum()

Year                                0
Country of origin                   0
Country of origin (ISO)           299
Country of asylum                   0
Country of asylum (ISO)             0
Refugees under UNHCR's mandate      0
Asylum-seekers                      0
IDPs of concern to UNHCR            0
Stateless persons                   0
Others of concern                   0
dtype: int64

In [17]:
df[df['Country of origin (ISO)'].isnull()]

,Year,Country of origin,Country of origin (ISO),Country of asylum,Country of asylum (ISO),Refugees under UNHCR's mandate,Asylum-seekers,IDPs of concern to UNHCR,Stateless persons,Others of concern
4579,2016,Unknown,NaN,Egypt,EGY,0,6,0,0,0
4580,2016,Unknown,NaN,Argentina,ARG,526,0,0,0,0
4581,2016,Unknown,NaN,Australia,AUS,22,46,0,0,0
4582,2016,Unknown,NaN,Austria,AUT,1933,1440,0,0,0
4583,2016,Unknown,NaN,Belgium,BEL,7503,4295,0,0,0
...,...,...,...,...,...,...,...,...,...,...
31362,2021,Unknown,NaN,Switzerland,CHE,1716,58,0,0,60
31363,2021,Unknown,NaN,Syrian Arab Rep.,SYR,5,0,0,0,0
31364,2021,Unknown,NaN,Turkey,TUR,515,10024,0,0,0
31365,2021,Unknown,NaN,United States of America,USA,6369,4160,0,0,0
31366,2021,Unknown,NaN,Zambia,ZMB,71,0,0,0,0

In [29]:
df.sort_values(by = 'Country of asylum')

,Year,Country of origin,Country of origin (ISO),Country of asylum,Country of asylum (ISO),Refugees under UNHCR's mandate,Asylum-seekers,IDPs of concern to UNHCR,Stateless persons,Others of concern
0,2016,Afghanistan,AFG,Afghanistan,AFG,0,0,1797551,0,114221
2029,2016,Iran (Islamic Rep. of),IRN,Afghanistan,AFG,33,16,0,0,0
20172,2019,Turkey,TUR,Afghanistan,AFG,0,79,0,0,0
26746,2021,Bangladesh,BGD,Afghanistan,AFG,0,5,0,0,0
14611,2018,Tajikistan,TJK,Afghanistan,AFG,0,7,0,0,0
...,...,...,...,...,...,...,...,...,...,...
16866,2019,Eritrea,ERI,Zimbabwe,ZWE,20,5,0,0,0
28889,2021,Kenya,KEN,Zimbabwe,ZWE,0,8,0,0,0
4111,2016,Sudan,SDN,Zimbabwe,ZWE,5,0,0,0,0
8009,2017,Mozambique,MOZ,Zimbabwe,ZWE,0,8059,0,0,0
31745,2021,Zimbabwe,ZWE,Zimbabwe,ZWE,0,0,0,0,141

In [30]:
df.drop(columns = ['Country of origin', 'Country of origin (ISO)'], inplace=True)

In [40]:
rf = df.groupby(['Year', 'Country of asylum', 'Country of asylum (ISO)'])["Refugees under UNHCR's mandate", 'Asylum-seekers',
       'IDPs of concern to UNHCR', 'Stateless persons', 'Others of concern'].sum().reset_index()

/var/folders/8c/d71xvtx971706d0ttvg_stb80000gn/T/ipykernel_59522/3054844471.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  rf = df.groupby(['Year', 'Country of asylum', 'Country of asylum (ISO)'])["Refugees under UNHCR's mandate", 'Asylum-seekers',

In [50]:
rf = rf.sort_values(by = ['Country of asylum', 'Year'])

In [51]:
rf.head(10)

,Year,Country of asylum,Country of asylum (ISO),Refugees under UNHCR's mandate,Asylum-seekers,IDPs of concern to UNHCR,Stateless persons,Others of concern
0,2016,Afghanistan,AFG,59770,123,1797551,0,114221
175,2017,Afghanistan,AFG,75927,215,1837079,0,448032
349,2018,Afghanistan,AFG,72228,281,2106893,0,489854
525,2019,Afghanistan,AFG,72227,247,2553390,0,447093
701,2020,Afghanistan,AFG,72278,167,2886317,0,82595
878,2021,Afghanistan,AFG,72226,187,3204805,0,84742
1,2016,Albania,ALB,141,2750,0,4921,0
176,2017,Albania,ALB,124,32,0,4460,2719
350,2018,Albania,ALB,132,159,0,4160,76
526,2019,Albania,ALB,120,5,0,3687,153

In [64]:
rf.to_csv('../../data/pop_refugees_clean.csv')